//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEstimator.Business.PEService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportRequest", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProEstimator.Business.PEService.Import))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProEstimator.Business.PEService.QueueImportRequest))]
    public partial class ImportRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DequeueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAdddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EnqueueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEstimator.Business.PEService.ImportFilter FilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeEstimatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEstimator.Business.PEService.Priority PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEstimator.Business.PEService.ImportSource SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEstimator.Business.PEService.ImportStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEstimator.Business.PEService.ImportType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeEstimatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DequeueDate {
            get {
                return this.DequeueDateField;
            }
            set {
                if ((this.DequeueDateField.Equals(value) != true)) {
                    this.DequeueDateField = value;
                    this.RaisePropertyChanged("DequeueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAdddress {
            get {
                return this.EmailAdddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAdddressField, value) != true)) {
                    this.EmailAdddressField = value;
                    this.RaisePropertyChanged("EmailAdddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EnqueueDate {
            get {
                return this.EnqueueDateField;
            }
            set {
                if ((this.EnqueueDateField.Equals(value) != true)) {
                    this.EnqueueDateField = value;
                    this.RaisePropertyChanged("EnqueueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEstimator.Business.PEService.ImportFilter Filter {
            get {
                return this.FilterField;
            }
            set {
                if ((this.FilterField.Equals(value) != true)) {
                    this.FilterField = value;
                    this.RaisePropertyChanged("Filter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((this.LoginIdField.Equals(value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeEstimates {
            get {
                return this.PeEstimatesField;
            }
            set {
                if ((this.PeEstimatesField.Equals(value) != true)) {
                    this.PeEstimatesField = value;
                    this.RaisePropertyChanged("PeEstimates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEstimator.Business.PEService.Priority Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEstimator.Business.PEService.ImportSource Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEstimator.Business.PEService.ImportStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrStatus {
            get {
                return this.StrStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StrStatusField, value) != true)) {
                    this.StrStatusField = value;
                    this.RaisePropertyChanged("StrStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEstimator.Business.PEService.ImportType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeEstimates {
            get {
                return this.WeEstimatesField;
            }
            set {
                if ((this.WeEstimatesField.Equals(value) != true)) {
                    this.WeEstimatesField = value;
                    this.RaisePropertyChanged("WeEstimates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Import", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class Import : ProEstimator.Business.PEService.ImportRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PEEstCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeRemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WebEstEstCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PEEstCount {
            get {
                return this.PEEstCountField;
            }
            set {
                if ((this.PEEstCountField.Equals(value) != true)) {
                    this.PEEstCountField = value;
                    this.RaisePropertyChanged("PEEstCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeRemaining {
            get {
                return this.TimeRemainingField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeRemainingField, value) != true)) {
                    this.TimeRemainingField = value;
                    this.RaisePropertyChanged("TimeRemaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WebEstEstCount {
            get {
                return this.WebEstEstCountField;
            }
            set {
                if ((this.WebEstEstCountField.Equals(value) != true)) {
                    this.WebEstEstCountField = value;
                    this.RaisePropertyChanged("WebEstEstCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueImportRequest", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class QueueImportRequest : ProEstimator.Business.PEService.ImportRequest {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportFilter", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    public enum ImportFilter : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Last3Years = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Priority", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    public enum Priority : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standard = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Priority")]
        PriorityMember = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportSource", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    public enum ImportSource : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebEst = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportStatus", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    public enum ImportStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportType", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    public enum ImportType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contracts = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Estimates = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueImportResponse", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class QueueImportResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueSizeRequest", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class QueueSizeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueueNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueueName {
            get {
                return this.QueueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QueueNameField, value) != true)) {
                    this.QueueNameField = value;
                    this.RaisePropertyChanged("QueueName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueSizeResponse", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class QueueSizeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueQueryRequest", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class QueueQueryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueueNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueueName {
            get {
                return this.QueueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QueueNameField, value) != true)) {
                    this.QueueNameField = value;
                    this.RaisePropertyChanged("QueueName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueQueryReponse", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class QueueQueryReponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEstimator.Business.PEService.Import[] ImportsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEstimator.Business.PEService.Import[] Imports {
            get {
                return this.ImportsField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportsField, value) != true)) {
                    this.ImportsField = value;
                    this.RaisePropertyChanged("Imports");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueProgressRequest", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class QueueProgressRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((this.LoginIdField.Equals(value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueProgressResponse", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class QueueProgressResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEstimator.Business.PEService.ImportProgressItem ImportProgressItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEstimator.Business.PEService.ImportProgressItem ImportProgressItem {
            get {
                return this.ImportProgressItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportProgressItemField, value) != true)) {
                    this.ImportProgressItemField = value;
                    this.RaisePropertyChanged("ImportProgressItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((this.LoginIdField.Equals(value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportProgressItem", Namespace="http://schemas.datacontract.org/2004/07/ProEstimator.Business.Model")]
    [System.SerializableAttribute()]
    public partial class ImportProgressItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProEstimatorEstimatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WebBestEstimatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProEstimatorEstimates {
            get {
                return this.ProEstimatorEstimatesField;
            }
            set {
                if ((this.ProEstimatorEstimatesField.Equals(value) != true)) {
                    this.ProEstimatorEstimatesField = value;
                    this.RaisePropertyChanged("ProEstimatorEstimates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WebBestEstimates {
            get {
                return this.WebBestEstimatesField;
            }
            set {
                if ((this.WebBestEstimatesField.Equals(value) != true)) {
                    this.WebBestEstimatesField = value;
                    this.RaisePropertyChanged("WebBestEstimates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PEService.IImportService")]
    public interface IImportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/AddImportToQueue", ReplyAction="http://tempuri.org/IImportService/AddImportToQueueResponse")]
        ProEstimator.Business.PEService.QueueImportResponse AddImportToQueue(ProEstimator.Business.PEService.QueueImportRequest account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/AddImportToQueue", ReplyAction="http://tempuri.org/IImportService/AddImportToQueueResponse")]
        System.Threading.Tasks.Task<ProEstimator.Business.PEService.QueueImportResponse> AddImportToQueueAsync(ProEstimator.Business.PEService.QueueImportRequest account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetQueueSize", ReplyAction="http://tempuri.org/IImportService/GetQueueSizeResponse")]
        ProEstimator.Business.PEService.QueueSizeResponse GetQueueSize(ProEstimator.Business.PEService.QueueSizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetQueueSize", ReplyAction="http://tempuri.org/IImportService/GetQueueSizeResponse")]
        System.Threading.Tasks.Task<ProEstimator.Business.PEService.QueueSizeResponse> GetQueueSizeAsync(ProEstimator.Business.PEService.QueueSizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/QueryQueue", ReplyAction="http://tempuri.org/IImportService/QueryQueueResponse")]
        ProEstimator.Business.PEService.QueueQueryReponse QueryQueue(ProEstimator.Business.PEService.QueueQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/QueryQueue", ReplyAction="http://tempuri.org/IImportService/QueryQueueResponse")]
        System.Threading.Tasks.Task<ProEstimator.Business.PEService.QueueQueryReponse> QueryQueueAsync(ProEstimator.Business.PEService.QueueQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetQueueProgress", ReplyAction="http://tempuri.org/IImportService/GetQueueProgressResponse")]
        ProEstimator.Business.PEService.QueueProgressResponse GetQueueProgress(ProEstimator.Business.PEService.QueueProgressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetQueueProgress", ReplyAction="http://tempuri.org/IImportService/GetQueueProgressResponse")]
        System.Threading.Tasks.Task<ProEstimator.Business.PEService.QueueProgressResponse> GetQueueProgressAsync(ProEstimator.Business.PEService.QueueProgressRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImportServiceChannel : ProEstimator.Business.PEService.IImportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportServiceClient : System.ServiceModel.ClientBase<ProEstimator.Business.PEService.IImportService>, ProEstimator.Business.PEService.IImportService {
        
        public ImportServiceClient() {
        }
        
        public ImportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProEstimator.Business.PEService.QueueImportResponse AddImportToQueue(ProEstimator.Business.PEService.QueueImportRequest account) {
            return base.Channel.AddImportToQueue(account);
        }
        
        public System.Threading.Tasks.Task<ProEstimator.Business.PEService.QueueImportResponse> AddImportToQueueAsync(ProEstimator.Business.PEService.QueueImportRequest account) {
            return base.Channel.AddImportToQueueAsync(account);
        }
        
        public ProEstimator.Business.PEService.QueueSizeResponse GetQueueSize(ProEstimator.Business.PEService.QueueSizeRequest request) {
            return base.Channel.GetQueueSize(request);
        }
        
        public System.Threading.Tasks.Task<ProEstimator.Business.PEService.QueueSizeResponse> GetQueueSizeAsync(ProEstimator.Business.PEService.QueueSizeRequest request) {
            return base.Channel.GetQueueSizeAsync(request);
        }
        
        public ProEstimator.Business.PEService.QueueQueryReponse QueryQueue(ProEstimator.Business.PEService.QueueQueryRequest request) {
            return base.Channel.QueryQueue(request);
        }
        
        public System.Threading.Tasks.Task<ProEstimator.Business.PEService.QueueQueryReponse> QueryQueueAsync(ProEstimator.Business.PEService.QueueQueryRequest request) {
            return base.Channel.QueryQueueAsync(request);
        }
        
        public ProEstimator.Business.PEService.QueueProgressResponse GetQueueProgress(ProEstimator.Business.PEService.QueueProgressRequest request) {
            return base.Channel.GetQueueProgress(request);
        }
        
        public System.Threading.Tasks.Task<ProEstimator.Business.PEService.QueueProgressResponse> GetQueueProgressAsync(ProEstimator.Business.PEService.QueueProgressRequest request) {
            return base.Channel.GetQueueProgressAsync(request);
        }
    }
}
