//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEstimatorData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProEstData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProEstData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProEstimatorData.Resources.ProEstData", typeof(ProEstData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align.
        /// </summary>
        internal static string OperationType_Align {
            get {
                return ResourceManager.GetString("OperationType_Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend.
        /// </summary>
        internal static string OperationType_Blend {
            get {
                return ResourceManager.GetString("OperationType_Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OperationType_Other {
            get {
                return ResourceManager.GetString("OperationType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhaul.
        /// </summary>
        internal static string OperationType_Overhaul {
            get {
                return ResourceManager.GetString("OperationType_Overhaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refinish.
        /// </summary>
        internal static string OperationType_Refinish {
            get {
                return ResourceManager.GetString("OperationType_Refinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string OperationType_Repair {
            get {
                return ResourceManager.GetString("OperationType_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string OperationType_Replace {
            get {
                return ResourceManager.GetString("OperationType_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;I.
        /// </summary>
        internal static string OperationType_RI {
            get {
                return ResourceManager.GetString("OperationType_RI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;R.
        /// </summary>
        internal static string OperationType_RR {
            get {
                return ResourceManager.GetString("OperationType_RR", resourceCulture);
            }
        }
    }
}
