//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEstimator.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProEstBusiness {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProEstBusiness() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProEstimator.Business.Resources.ProEstBusiness", typeof(ProEstBusiness).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were sent this email on behalf of [[COMPANY_NAME]].
        /// </summary>
        internal static string EmailFooterLine1 {
            get {
                return ResourceManager.GetString("EmailFooterLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-Est : 12884 S Frontrunner Blvd, Ste 220 Draper, UT 84020 | (888) 932-3780 | info@web-est.com.
        /// </summary>
        internal static string EmailFooterLine2 {
            get {
                return ResourceManager.GetString("EmailFooterLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account disabled, please contact customer service.
        /// </summary>
        internal static string Login_Error_AccountDisabled {
            get {
                return ResourceManager.GetString("Login_Error_AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of users are already logged in for this account.  If you press the login button again you will be logged in and the oldest session will be logged off..
        /// </summary>
        internal static string Login_Error_AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("Login_Error_AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all 3 fields.
        /// </summary>
        internal static string Login_Error_EnterAllFields {
            get {
                return ResourceManager.GetString("Login_Error_EnterAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with that user name and organization was not found..
        /// </summary>
        internal static string Login_Error_NotFound {
            get {
                return ResourceManager.GetString("Login_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login credentials..
        /// </summary>
        internal static string Login_Error_UserNotFound {
            get {
                return ResourceManager.GetString("Login_Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password..
        /// </summary>
        internal static string Login_Error_WrongPassword {
            get {
                return ResourceManager.GetString("Login_Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be at least 4 characters long..
        /// </summary>
        internal static string Message_PasswordMinLength {
            get {
                return ResourceManager.GetString("Message_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will no longer receive email alerts when your auto-pay payments fail..
        /// </summary>
        internal static string OptOutAutoPaySuccess {
            get {
                return ResourceManager.GetString("OptOutAutoPaySuccess", resourceCulture);
            }
        }
    }
}
