/*CREATE TABLE [dbo].[VehicleBodyMapping](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BodyCode] [varchar](2) NULL,
	[Description] [varchar](50) NULL,
	[BodyID] [int] NULL
) ON [PRIMARY]*/

Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('CP', 'Coupe', 13)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('CV', 'Convertible', 414)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('C4', 'Coupe 4 Dr.', 424)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('HB', 'Hatchback', 98)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('HT', 'Hardtop', 99)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('PK', 'Pickup', 16)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('SB', 'Sport Hatchback', 586)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('SC', 'Sport Coupe', 381)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('SD', 'Sedan', 413)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('SV', 'Sport Van', 137)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('SW', 'Station Wagon', 97)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('UT', 'Utility', 115)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('WW', 'Wide Wheel Wagon', 190)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('2D', 'Sedan 2 Dr.', 80)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('2F', 'Formal Hardtop 2 Dr.', 15)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('2H', 'Hatchback 2 Dr.', 14)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('2P', 'Pillard Hardtop 2 Dr.', 15)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('2T', 'Hardtop 2 Dr.', 15)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('2W', 'Wagon 2 Dr.', 96)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('3P', 'Coupe 3 Dr.', 381)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('4D', 'Sedan 4 Dr.', 114)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('4H', 'Hatchback 4 Dr.', 98)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('4P', 'Pillard Hardtop 4 Dr.', 99)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('4T', 'Hardtop 4 Dr.', 99)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('4W', 'Wagon 4 Dr.', 129)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('5D', 'Sedan 5 Dr.', 413)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('CG', 'Cargo Van', 164)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('CS', 'Super Cab / Chassis Pickup', 101)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('CU', 'Custom Pickup', 16)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('CW', 'Crew Pickup', 101)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('CY', 'Cargo Cutaway', 131)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('EC', 'Extended Cargo Van', 173)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('ES', 'Extended Sport Van', 159)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('EV', 'Ext Van', 159)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('EW', 'Extended Window Van', 199)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('IE', 'Incomplete Ext Van', 159)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('MV', 'Maxi Van', 137)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('MY', 'Motorized Cutaway', 131)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('PC', 'Club Cab Pickup', 101)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('PM', 'Pickup with Camper mounted on bed', 16)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('PS', 'Super Cab Pickup', 101)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('SN', 'Step Van', 137)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('SP', 'Sport Pickup', 101)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('VC', 'Van Camper', 137)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('VD', 'Display Van', 177)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('VN', 'Van', 137)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('VT', 'Vanette (including Metro and Handy Van)', 137)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('VW', 'Window Van', 194)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('YY', 'Cutaway', 131)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('3B', '3 Door Extended Cab / Chassis', 58)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('3C', '3 Door Extended Cab Pickup', 58)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('4B', '4 Door Extended Cab / Chassis', 508)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('4C', '4 Door Extended Cab Pickup', 508)
Insert Into VehicleBodyMapping(BodyCode, Description, BodyID) Values('8V', '8 Passenger Sport Van', 137)
